// JSON.stringify(Array.from(document.querySelectorAll("path,g")).map(k => k.id).filter(Boolean))
export const highlightIDs = [
  "wc",
  "meeting_kari",
  "meeting_b31",
  "meeting_aalto",
  "meeting_meri",
  "meeting_luoto",
  "meeting_kaisla",
  "meeting_myrsky",
  "quietArea",
  "servicePoint",
  "kela",
  "popup",
  "kohtaamo",
  "paja",
  "stage",
  "studio",
  "playingRoom",
  "music",
  "childrenBooks",
  "kidsLibraryInfo",
  "info",
  "kidsPlayground",
  "yesBox",
  "VOX",
  "elevators",
  "escalator",
  "childrenHealthCare",
  "mehilainenDental",
  "husLabXRay",
  "mentalHealthCenter",
  "healthCareCenter",
];

export const highlightNames = {
  VOX: "VOX Youth Space",
  yesBox: "YesBox",
  kidsPlayground: "Playground",
  kidsLibraryInfo: "Kids library info",
  childrenBooks: "Children's books",
  paja: "Makerspace",
  studio: "Music studio",
  playingRoom: "Music playing room",
  kohtaamo: "Kohtaamo",
  stage: "Stage",
  healthCareCenter: "Healthcare center",
  mentalHealthCenter: "Mental health and addiction services",
  childrenHealthCare: "Child health center",
  mehilainenDental: "Mehiläinen dental care center",
  husLabXRay: "HUSLab X-ray",
  kela: "KELA",
  servicePoint: "Espoo city service point",
  meeting_kari: "Kari",
  meeting_aalto: "Aalto",
  meeting_meri: "Meri",
  meeting_luoto: "Luoto",
  meeting_kaisla: "Kaisla",
  meeting_myrsky: "Myrsky",
  info: "Info",
  quietArea: "Quiet area",
  wc: "Toilets",
  escalator: "Escalator",
  elevators: "Elevators",
  popup: "Popup",
};
