// JSON.stringify(Array.from(document.querySelectorAll("path")).map(k => k.id).filter(Boolean))
export const highlightIDs = [
  "bcg",
  "childrenHealthCare",
  "yesBox",
  "info",
  "kidsLibraryInfo",
  "kidsArea",
  "studio",
  "musicRoom",
  "stage",
  "paja",
  "ypp",
  "meetingSpace",
  "kela",
  "healthCareCenter",
  "quietArea",
  "VOX",
  "elevators",
  // "outline",
  "rtg",
  "dentalClinic",
  "mentalHealthCenter",
  "mentalHealthCenter1",
  "childrenBooks",
  "music",
];
